// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.28;

enum Scenario {
    MINT_WITH_BORROW_DEPOSIT_FLASH_LOAN,
    MINT_WITH_BORROW_NO_FLASH_LOAN,
    MINT_WITH_BORROW_WITHDRAW_FLASH_LOAN,
    MINT_WITH_COLLATERAL_DEPOSIT_FLASH_LOAN,
    MINT_WITH_COLLATERAL_NO_FLASH_LOAN,
    MINT_WITH_COLLATERAL_WITHDRAW_FLASH_LOAN,
    REDEEM_WITH_BORROW_DEPOSIT_FLASH_LOAN,
    REDEEM_WITH_BORROW_NO_FLASH_LOAN,
    REDEEM_WITH_BORROW_WITHDRAW_FLASH_LOAN,
    REDEEM_WITH_COLLATERAL_DEPOSIT_FLASH_LOAN,
    REDEEM_WITH_COLLATERAL_NO_FLASH_LOAN,
    REDEEM_WITH_COLLATERAL_WITHDRAW_FLASH_LOAN
}